general:
  inferBuildTool: true
steps:
#  mtaBuild:
#    buildTarget: 'CF'
  
  cloudFoundryDeploy:
    deployTool: 'mvn'
    deployType: 'standard'
    cloudFoundry:
      org: 'a004cb52trial'
      space: 'dev'
      credentialsId: 'CF_IDENTITY_FOR_JENKINS'